export const reqData = {
  code: 200,
  msg: '查询成功',
  data: {
    total: 112,
    rows: [
      {
        id: '2024020500001',
        createBy: '1',
        createTime: '2024-02-05 13:55:47',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-03-27 14:02:02',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '科室借货',
        configType: '科室借货',
        configName: '消耗计费时是否产生科室借货',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=material_charge_borrow_record_setting&type=material_charge_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院运营管理，设置消耗计费是否生成借货记录',
      },
      {
        id: '2021082710001',
        createBy: '1',
        createTime: '2022-07-04 11:40:26',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-04-10 13:33:26',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '需求设置',
        configType: '新建需求计划时，单价如何显示设置',
        configName: '新建需求计划时，单价如何显示设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/MaterialReferPriceSource?categoryCode=require_setting&type=material_refer_price_source_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark:
          '备注：根据医院实际运营管理需求，设置不同物资类型的耗材在新建、修改需求计划时，单价是如何取值的；\r\n如果设置为“取供货清单”则取供货清单里面的单价；如果设置为“规格耗材参考单价”则是取值于规格耗材里面的参考单价；\r\n同时，如果设定的单价取值于最新供货清单，则在创建规格耗材字典时，参考单价为非必填项；如果设设定的是单价取耗材参考单价，则创建规格耗材字典时，参考单价为必填项；',
      },
      {
        id: '1605c473d0001f6',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-04-10 09:47:41',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '收费耗材出库',
        configType: 'HIS计费设置',
        configName: '收费耗材出库设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=material_consume_setting,material_consume_contrast_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '根据医院的实际运营管理，设置收费耗材没有对照关系或者对照关系停用是否可以正常出库',
      },
      {
        id: '1605c473d345329',
        createBy: '1',
        createTime: '2022-10-24 11:55:15',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-04-10 22:29:30',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '需求计划',
        configType: '其他',
        configName: '智能补货时，是否自动生成采购计划',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=require_setting&type=auto_purchase_plan_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '根据医院的实际运营管理，设置审核智能补货时，是否同时生成采购计划',
      },
      {
        id: '202401190939002',
        createBy: '1',
        createTime: '2024-01-19 13:18:20',
        updateBy: '202306301749022vpcug9fo',
        updateTime: '2024-04-11 10:30:23',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '采购计划',
        configType: '其他',
        configName: '指定物资类型，按照非医疗业务处理流程',
        pageAddress:
          '{"type":"select","multiple":"Y","dictKey":"material_use_type","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=not_medical_material_value_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员の一',
        remark: '根据医院运营管理，指定物资类型，按照非医疗业务处理流程',
      },
      {
        id: '1605c473d0001e3',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-04-02 09:47:41',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '退费设置',
        configType: 'HIS计费设置',
        configName: 'HIS冲账后耗材是否自动退货',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=auto_return_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际运营管理需求，设置计费耗材冲账之后是否自动退货',
      },
      {
        id: '2024011819550002',
        createBy: '1',
        createTime: '2024-01-18 20:04:06',
        updateBy: '20230313150637mjilmrtku',
        updateTime: '2024-01-29 10:29:53',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '科室成本',
        configType: '科室成本',
        configName: '科室成本明细中的his计费人是否显示',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=dept_cost_setting&type=his_charge_user_show_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '韩雪敏',
        remark: '根据医院运营管理，设置科室成本明细中的his计费人是否显示',
      },
      {
        id: '20230905162200001',
        createBy: '1',
        createTime: '2023-09-06 10:21:52',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-04-09 17:59:37',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '耗材调拨',
        configType: '单据审核设置',
        configName: '耗材调拨单审核设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/MaterialAllotBillAuthSetting?categoryCode=department_setting&type=material_allot_rule_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员1',
        remark: '根据医院实际运营管理需求，设置耗材调拨单是否需要审核',
      },
      {
        id: '202310191308394081700d56975',
        createBy: '1',
        createTime: '2023-10-30 15:28:20',
        updateBy: '20230606145705fei68vd2l',
        updateTime: '2024-04-02 13:48:03',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '德宝云数据下发',
        configType: '德宝云数据下发',
        configName: '德宝云数据下发设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=data_trans_down_setting&type=organization_basic_info_setting,manufacture_basic_info_setting,production_image_setting,production_specification_setting,material_register_setting,province_code_setting,medical_insurance_code_setting,udi_primary_code_setting,supplies_contract_authorize_time_setting,drug_delivery_id_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '含-超管',
        remark: '根据医院实际运营管理需求，设置德宝云数据下发的流程',
      },
      {
        id: '1605c473d0001e1',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-03-18 17:58:11',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '小数位数设置',
        configType: '其它',
        configName: '单价金额数量小数位数设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=system_setting&type=decimal_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '根据医院实际运营管理需求，可以配置系统中涉及金额显示的小数位数，四舍五入显示',
      },
      {
        id: '1605c473d000113',
        createBy: '0',
        createTime: '2022-02-22 16:49:26',
        updateBy: '1',
        updateTime: '2024-01-22 09:56:52',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '耗材设置',
        configType: '耗材分类设置',
        configName: '耗材分类设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/materialKindSetting?categoryCode=material_setting&type=material_category_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '超级管理员',
        remark:
          '根据医院实际运营管理需求，设置核算科目,管理分类,药监分类取值于耗材管理里面的哪一分类',
      },
      {
        id: '20230330102308bbf2b40045',
        createBy: '1',
        createTime: '2023-03-30 09:20:49',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-02-01 16:16:44',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '退费设置',
        configType: 'his计费设置',
        configName: 'his退费自动处理时，退费单价跟最新单价是否一致设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=auto_refund_price_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '根据医院实际运营管理需求，设置his退费自动处理时，退费单价跟最新单价是否必须一致',
      },
      {
        id: 'cwj202207251435',
        createBy: '1',
        createTime: '2022-08-03 11:32:32',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-04-07 10:03:22',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '采购计划',
        configType: '单据审核设置',
        configName: '采购计划审核设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=audit_leve_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '根据医院的实际运营管理需求，设置符合要求的审核流程',
      },
      {
        id: '202312060007',
        createBy: '1',
        createTime: '2023-12-08 07:03:10',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-04-10 13:33:26',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '供货清单',
        configType: '供货清单',
        configName: '供货清单调价审核设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=supplies_contract_detail_setting&type=adjust_price_audit_yn"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院运营管理，设置供货清单调价是否需要审核',
      },
      {
        id: '1605c473d0001ee',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '退货',
        configType: '其它',
        configName: '退货范围设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=material_scope_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际运营管理需求，设置耗材退货范围',
      },
      {
        id: '2021080500001',
        createBy: '1',
        createTime: '2021-09-09 18:17:49',
        updateBy: '20231011090805of0sm5y04',
        updateTime: '2024-04-10 15:04:36',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '人员设置',
        configType: '人员设置',
        configName: '入库单出库单人员设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/OutOrderPreparer?categoryCode=person_setting&type=in_out_person_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '任良硕',
        remark:
          '备注：请设置每一个中心仓入库单、出库单各个环节的人员；其中物的入库验收人、物的出库制单人是指系统自动生成的物的入库单、出库单；账的入库单、出库单制单人是指立即建账系统自动生成的账的入库单、出库单',
      },
      {
        id: '1605c473d000768',
        createBy: '1',
        createTime: '2022-03-29 12:07:24',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-03-29 17:35:01',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '需求计划',
        configType: '库存耗材申请设置',
        configName: '是否自动生成草稿状态的配送单',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=require_setting&type=draft_out_warehouse_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark:
          '根据医院实际运营管理需求，设置科室库存耗材申请审核通过之后，是否自动生成草稿状态的配送单',
      },
      {
        id: '1605c473d0001dc',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-04-01 13:52:49',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '需求计划',
        configType: '其它',
        configName: '需求计划调用库房耗材目录设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=require_setting&type=material_source_setting,material_scope_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '根据医院实际运营管理需求，设置科室护士下计划调用库房耗材目录的范围',
      },
      {
        id: '202307191400',
        createBy: '1',
        createTime: '2023-07-19 14:14:10',
        updateBy: '20240409173635ht4tdjn2i',
        updateTime: '2024-04-09 17:38:43',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '采购计划',
        configType: '采购范围设置',
        configName: '采购范围设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/purchaseScopeSetting?categoryCode=purchase_setting&type=purchase_scope_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员十',
        remark: '根据医院运营管理，设置用户的采购范围',
      },
      {
        id: '202308221113000001',
        createBy: '1',
        createTime: '2023-08-23 15:37:12',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-04-09 18:00:22',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '科室结账',
        configType: '其它',
        configName: '科室结账时,结账单中耗材单价的取值设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/departmentSettlePriceValue?categoryCode=department_setting&type=material_price_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员1',
        remark: '根据医院运营管理，设置科室结账时，结账单中的耗材单价的取值',
      },
      {
        id: '202105070000001',
        createBy: '1',
        createTime: '2021-05-07 17:24:36',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-04-03 14:02:28',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'HIS计费',
        configType: '其他',
        configName: 'HIS成本科室库房跟库存科室库房是否必须一致',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=costdept_stockdept_same_yn"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '王喵喵1',
        remark:
          '备注：“根据医院实际运营管理需求设置是否允许科室借货，如果设置为“是”，代表一物一码耗材在his计费出库时，成本科室库房和库存科室库房可以不一致；如果设置为“否”代表一物一码耗材在his计费出库时，成本科室库房跟库存科室库房必须一致”。',
      },
      {
        id: '20240308141110795800',
        createBy: '1',
        createTime: '2024-03-08 14:39:51',
        updateBy: '20230313150637mjilmrtku',
        updateTime: '2024-04-01 13:16:17',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '其它',
        configType: '其它',
        configName: '临采耗材相关设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/BackReturnRange?categoryCode=temporary_purchase_setting&type=temporary_purchase_limit_add_audit_setting,temporary_purchase_limit_update_audit_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '韩雪敏',
        remark: '根据医院实际运营管理需求，设置临采耗材相关的自定义配置',
      },
      {
        id: '2022021400001',
        createBy: '1',
        createTime: '2022-03-29 12:06:04',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-04-10 16:42:55',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '基础数据',
        configType: '基础数据设置',
        configName: '基础数据停用影响设置',
        pageAddress:
          '{"type":"page","path":"/operation/help?categoryCode=basic_data_setting&type=basic_data_stop_affect_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark:
          '根据医院实际运营管理需求，设置规格耗材字典、供货清单等基础数据停用对需求、采购、入库、配送、消耗等流程的影响',
      },
      {
        id: '1605c473d0001e9',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '1',
        updateTime: '2024-04-11 11:02:36',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '配送出库',
        configType: '自动生成配送单',
        configName: '带科室的验收单是否自动生成中心仓出库单的设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=auto_deliver_setting,auto_deliver_default_value_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '超级管理员',
        remark: '根据医院实际运营管理需求，设置带科室的验收单是否自动生成中心仓出库单',
      },
      {
        id: '202306070001',
        createBy: '1',
        createTime: '2023-06-07 01:32:23',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-01-29 10:52:23',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '配送出库',
        configType: '其他',
        configName: '配送出库调用需求计划时，库存排除的入库类型',
        pageAddress:
          '{"type":"select","multiple":"Y","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=invoke_require_plan2deliver_entry_type_excluding_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '备注：根据医院运营管理需求设置配送出库调用需求计划时，排除的入库类型',
      },
      {
        id: '202309041421000001',
        createBy: '1',
        createTime: '2023-09-04 14:29:31',
        updateBy: '20240410145419u6pkzn7p5',
        updateTime: '2024-04-10 14:54:42',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '供货清单',
        configType: '供货清单',
        configName: '同一耗材供货清单数量设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=supplies_contract_detail_setting&type=supplies_contract_detail_num_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '接口测试',
        remark: '根据医院运营管理，设置同一耗材是否允许存在多个供货清单',
      },
      {
        id: '2023061211020',
        createBy: '1',
        createTime: '2023-06-12 13:12:13',
        updateBy: '20230221190256texemg0a6',
        updateTime: '2023-08-31 18:35:45',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '科室成本',
        configType: '科室成本',
        configName: '科室期初耗材生成的科室成本是否可以进行结账',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=dept_cost_setting&type=dept_cost_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: 'wjl',
        remark: '根据医院运营管理，设置科室期初耗材生成的成本是否可以进行结账',
      },
      {
        id: '202308210953000001',
        createBy: '1',
        createTime: '2023-08-21 10:05:43',
        updateBy: '20210928155804dfm8cu9y5',
        updateTime: '2024-03-29 16:30:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '定数包',
        configType: '其它',
        configName: '定数包打包设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=fix_package_setting&type=different_batch_pick_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王金磊',
        remark: '根据医院实际运营管理,设置不同批次的散货是否可以打成一个定数包',
      },
      {
        id: '1605c473d0001ec',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-03-29 14:32:47',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '科室借货',
        configType: '科室借货',
        configName: '科室借货退费时，设置耗材库存返回借入还是借出科室',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=department_setting&type=material_borrow_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院实际运营管理需求，设置科室借货耗材退费之后，库存退回到哪一个科室库存',
      },
      {
        id: '1605c473d0001d6',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-04-09 18:01:36',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '结账单',
        configType: '拆单',
        configName: '结账单拆单设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/SettleAccountSplitSetting?categoryCode=department_setting&type=charge_split_rule_setting,material_kind_split_rule_setting,material_account_kind_split_rule_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员1',
        remark: '根据医院实际运营管理需求，设置结账单的拆单规则',
      },
      {
        id: '1605c473d000329',
        createBy: '1',
        createTime: '2022-05-13 18:00:55',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-03-07 09:13:07',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '科室管理',
        configType: '科室报废耗材的范围设置',
        configName: '科室报废耗材的范围',
        pageAddress:
          '{"type":"page","path":"/systemSetting/MaterialScrapSet?categoryCode=department_setting&type=material_scrap_range_setting,material_scrap_range_setting_2"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际运营管理需求，设置科室报废耗材的范围',
      },
      {
        id: '2024032515090001',
        createBy: '1',
        createTime: '2024-03-26 09:31:55',
        updateBy: '20231011090805of0sm5y04',
        updateTime: '2024-03-26 09:39:27',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '第三方系统',
        configType: '系统集成设置',
        configName: '第三方地址配置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/SSOLogin?categoryCode=system_integration_setting&type=third_party_url_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '任良硕',
        remark: '用于配置与spd系统有集成需要的第三方系统的url',
      },
      {
        id: '20230604102308bbf2b40045',
        createBy: '1',
        createTime: '2023-06-04 09:20:49',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-02-23 16:20:31',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '计费设置',
        configType: 'HIS计费设置',
        configName: 'webservice计费，spd单价跟his单价是否必须一致',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=webservice_price_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark:
          '根据医院实际运营需求,设置耗材使用webservice方式消耗出库时，spd单价跟his单价是否必须一致',
      },
      {
        id: '1605c473d0001f3',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '智能柜',
        configType: '系统集成设置',
        configName: '智能柜集成配置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/IntelligentCabinetSet?categoryCode=hardware_setting&type=cab_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '配置后可以连接智能柜接口，实现智能柜科室使用',
      },
      {
        id: '1605c473d0001df',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '规格耗材字典',
        configType: '其它',
        configName: '规格耗材字典规格型号设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=material_setting&type=material_spec_model_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际运营管理需求，设置规格耗材字典规格型号管理的精细程度',
      },
      {
        id: '1605c473dddd314',
        createBy: '1',
        createTime: '2022-04-21 16:54:29',
        updateBy: '20231011090805of0sm5y04',
        updateTime: '2024-04-11 10:40:12',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '采购计划',
        configType: '采购设置',
        configName: '新建采购的时候是否显示科室库',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=is_department_warehouse"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '任良硕',
        remark: '根据医院实际运营管理需求，设置新建采购的时候是否显示科室库',
      },
      {
        id: '1605c473d0001e0',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-03-29 14:32:14',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '计费设置',
        configType: 'HIS计费设置',
        configName: '计费耗材自动出库，成本单价跟his收费单价是否一致的设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=material_price_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院实际运营需求,设置计费耗材出库时，成本单价跟his收费单价是否必须一致',
      },
      {
        id: '2021101100002',
        createBy: '1',
        createTime: '2022-03-05 17:39:30',
        updateBy: '1',
        updateTime: '2024-04-09 16:53:12',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '供应商设置',
        configType: '拆单设置',
        configName: '账入库单拆单设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/AccountWarehousingSplitOrder?categoryCode=organization_setting&type=account_entry_split_rule_setting,province_purchase_yn_split_rule_setting,account_entry_split_rule_paytype_setting,account_entry_split_rule_custom_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '超级管理员',
        remark: '根据医院实际运营管理需求，设置帐入库单的拆单规则',
      },
      {
        id: '1605c473d0001d3',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-03-29 13:47:26',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '采购计划',
        configType: '其它',
        configName: '采购合同管控设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=contract_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院实际运营管理要求，设置采购计划是否受合同设置',
      },
      {
        id: '202308110001',
        createBy: '1',
        createTime: '2023-08-11 03:20:38',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-04-07 13:48:09',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'SPD计费',
        configType: 'SPD计费',
        configName: 'spd计费科室来源设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/spdChargDepartment?categoryCode=spd_charge_department_source_setting&type=operation_department_source,perform_department_source,order_department_source,operation_department_source_update_yn,perform_department_source_update_yn,order_department_source_update_yn"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '根据医院运营管理，设置spd计费时，科室来源',
      },
      {
        id: '2021101410000',
        createBy: '1',
        createTime: '2021-10-26 12:30:01',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-03-29 14:36:00',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '计费设置',
        configType: 'HIS计费设置',
        configName: '科室高值备货类耗材消耗计费之后，是否自动补科室需求计划',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=auto_create_require_plan"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '洪燕',
        remark:
          '根据医院实际运营管理要求，设置科室高值备货类耗材消耗计费之后，是否自动补科室需求计划单；如果设置为“是”，则spd消耗计费成功之后，会自动生成对应高值备货类耗材草稿状态的需求计划单；如果设置为“否”，spd消耗计费成功之后，也不会自动生成对应高值备货类耗材草稿状态的需求计划单。',
      },
      {
        id: '202306200919',
        createBy: '1',
        createTime: '2023-06-20 09:34:25',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-04-07 16:48:28',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '文件服务器设置',
        configType: '其他',
        configName: '文件服务器设置',
        pageAddress:
          '{"type":"input","path":"/basic/systemsetting/detail.ac?categoryCode=system_setting&type=minio_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员1',
        remark: '根据医院实际运营管理需求，设置文件服务器地址',
      },
      {
        id: '202305170001',
        createBy: '1',
        createTime: '2023-05-17 10:16:28',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-03-29 14:33:14',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'HIS计费',
        configType: 'HIS计费设置',
        configName: 'HIS计费自动处理时，送达核算耗材的计费/退费记录是否自动关闭',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=no_barcode_deliver_pay_auto_close_yn_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark:
          '根据医院运营管理需求设置HIS计费/退费时，待处理的送达核算耗材数据是否自动关闭（不包含一物一码耗材）',
      },
      {
        id: '1605c473d0001da',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210928155804dfm8cu9y5',
        updateTime: '2024-03-29 16:46:26',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '配送出库单',
        configType: '单据审核设置',
        configName: '配送出库单审核设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=audit_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王金磊',
        remark: '根据医院实际运营管理需求，设置配送出库单审核设置',
      },
      {
        id: '1605c473d0001d8',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210928155804dfm8cu9y5',
        updateTime: '2024-03-29 16:46:26',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '验收单',
        configType: '单据审核设置',
        configName: '验收单审核设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=entry_audit_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王金磊',
        remark: '根据医院实际运营管理需求，设置验收单审核设置',
      },
      {
        id: '2023062700001',
        createBy: '1',
        createTime: '2023-06-27 18:13:53',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-07-05 16:14:22',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '消耗出库',
        configType: '其它',
        configName: '消耗出库查询数据时科室取值标准设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/ConsumeOutDepartmentStandards?categoryCode=consume_dept_scope_setting&type=consume_query_dept_scope_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark:
          '根据医院运营管理，设置消耗出库数据查询时按用户授权科室是在”开单科室、执行科室还是计费科室“下进行查询',
      },
      {
        id: 'e2c45e9d-1ec5-11ed-86cd-782bcb3e2f23',
        createBy: '1',
        createTime: '2022-10-24 12:08:59',
        updateBy: '20230227161240ze9whs9r0',
        updateTime: '2023-05-16 17:53:17',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'his对照',
        configType: 'his对照设置',
        configName: '临采耗材是否自动对照设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_setting&type=his_contrast_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '张大千',
        remark: '根据医院的实际运营管理需求，设置临采耗材是否自动进行his对照',
      },
      {
        id: '2022062300002',
        createBy: '1',
        createTime: '2022-01-23 23:16:53',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-03-29 14:50:39',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'HIS计费',
        configType: 'HIS计费设置',
        configName: 'HIS条码计费自动处理时核算方式必须计费核算',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=barcode_charge_pay_type_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: 'HIS传来的条码计费信息在自动处理的时候耗材的核算方式是否必须计费核算',
      },
      {
        id: '202403111342000001',
        createBy: '1',
        createTime: '2024-03-11 13:42:47',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-04-01 10:12:19',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '其它',
        configType: '其它',
        configName: '计算公式维护',
        pageAddress:
          '{"type":"page","path":"/systemSetting/CalculationFormulaSetting?categoryCode=calculation_formula_setting&type=ai_require_plan_replenishment_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '洪燕',
        remark: '根据医院实际运营管理需求，设置不同的计算公式',
      },
      {
        id: '2023062600001',
        createBy: '1',
        createTime: '2023-06-26 15:25:50',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2023-11-24 11:15:48',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '监管程序',
        configType: '其它',
        configName: '监管月报分类设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/MonthlyReportConsumables?categoryCode=regulatory_program_setting&type=account_report_kind_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '根据医院运营管理，设置监管月报中的分类',
      },
      {
        id: '1605c473d0001e4',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230518111814w7xtv6sl9',
        updateTime: '2023-08-28 11:15:03',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '院内码',
        configType: '打印设置',
        configName: '院内码打印设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/BarCodePrintSet?categoryCode=print_setting&type=barcode_print_setting,fix_package_print_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '玄其超',
        remark: '根据医院实际运营管理需求，设置院内码普通条码的打印张数',
      },
      {
        id: '1605c473d132223',
        createBy: '1',
        createTime: '2022-06-07 18:17:43',
        updateBy: '20210928155804dfm8cu9y5',
        updateTime: '2024-03-29 15:29:16',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '入库验收',
        configType: '其他',
        configName: '入库验收审核通过之后，是否自动弹出对应的配送出库',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=auto_jump_deliver_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王金磊',
        remark:
          '备注：根据医院的实际运营管理需求，设置入库单审核通过之后，是否自动弹出对应的配送单',
      },
      {
        id: '2021112900001',
        createBy: '1',
        createTime: '2021-12-20 16:54:00',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-04-03 15:41:40',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'HIS计费',
        configType: 'HIS计费设置',
        configName: '退费时是否允许部分退费',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=partial_refund_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '王喵喵1',
        remark:
          '备注：根据医院实际运营管理需求，设置退费的时候，是否允许部分退费；如果设置为“是”则代表一条计费记录里面的耗材可以进行多次退费，如果设置为“否”代表一条计费记录里面的耗材只能一次全部退费完成。',
      },
      {
        id: '202312060001',
        createBy: '1',
        createTime: '2023-12-13 08:55:07',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-04-11 09:40:59',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '准入管理',
        configType: '准入审核',
        configName: '规格耗材及供货清单准入审核设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/materialDictionaryAndSupplyEntryAudit?categoryCode=access_management_setting&type=add_material_audit_yn,add_contract_audit_yn,add_material_and_contract_audit_scope_charge_style,audit_add_material_then_audit_add_contract,audit_add_contract_then_audit_add_material"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院运营管理，设置规格耗材、供货清单准入审核规范',
      },
      {
        id: '2022062200001',
        createBy: '1',
        createTime: '2022-07-04 11:40:17',
        updateBy: '20230227161240ze9whs9r0',
        updateTime: '2024-04-07 18:12:34',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '系统设置',
        configType: '单价设置',
        configName: '寄售耗材单价取值设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/SaleMaterialPriceSetting?categoryCode=system_setting&type=sale_material_price_setting,sale_material_stock_price_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '张大千',
        remark:
          '根据医院运营管理需求，设置非立即建账-寄售耗材，生成科室成本、供应商退货时，单价如何取值',
      },
      {
        id: '2023121400001',
        createBy: '1',
        createTime: '2023-12-14 10:10:14',
        updateBy: '20230313150637mjilmrtku',
        updateTime: '2024-03-27 09:58:50',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '其它',
        configType: '其它',
        configName: '待审核业务通知设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/WaitAuditBusinessNoticeSetting?categoryCode=notice_setting&type=wait_audit_business_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '韩雪敏',
        remark: '根据医院运营管理，设置待审核业务的通知要求',
      },
      {
        id: '1605c473d000203',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '1',
        updateTime: '2023-12-13 15:35:36',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '账簿',
        configType: '其它',
        configName: '账簿的自定义配置',
        pageAddress: '{"type":"page","path":"/systemSetting/AccountBookSet"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '超级管理员',
        remark: '根据医院的实际运营要求，添加账簿名称及每一个账簿下统计的核算科目的一级分类',
      },
      {
        id: '1605c473d0001d0',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '医院设置',
        configType: '医院设置',
        configName: '医院设置',
        pageAddress:
          '{"type":"img","path":"/basic/systemsetting/detail.ac?categoryCode=system_setting&type=background_pic_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际运营管理需求，可以设置每家医院的登录背景',
      },
      {
        id: '1605c473d0001d9',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-03-28 15:22:25',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '退货单',
        configType: '单据审核设置',
        configName: '退货单审核设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=audit_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '根据医院实际运营管理需求，设置退货单审核设置',
      },
      {
        id: '1605c473d0001f2',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '1',
        updateTime: '2023-05-24 16:01:55',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '云平台',
        configType: '系统集成设置',
        configName: '云平台集成配置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/CloudPlatformSet?categoryCode=cloud_interface_setting&type=colud_plateform_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '超级管理员【江北人民医院】',
        remark: '配置后可以连接云平台接口，实现业务协同',
      },
      {
        id: '1605c473d0001ff',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '人员设置',
        configType: '人员设置',
        configName: '调价出入库操作人设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=person_setting&type=adjust_price_person_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际需求，设置供应商更户的时候，中间补的是单据的操作人',
      },
      {
        id: '2021082700001',
        createBy: '1',
        createTime: '2021-09-07 18:15:50',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '耗材设置',
        configType: '科室报损耗材范围设置',
        configName: '科室报损耗材范围设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/DepartmentReportLossRange?categoryCode=material_setting&type=report_loss_scope_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '测试人员',
        remark: '备注: 根据医院的实际运营需求,设置科室报损的耗材范围',
      },
      {
        id: '202105080000002',
        createBy: '1',
        createTime: '2021-05-08 10:01:26',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '系统设置',
        configType: '盘点设置',
        configName: '盘亏出库默认科室设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=system_setting&type=inventory_loss_department_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院的实际运营管理需求，设置中心仓盘亏时，盘亏出库默认科室',
      },
      {
        id: '1605c473d0001d1',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-01-09 16:36:49',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '需求计划',
        configType: '拆单',
        configName: '需求计划拆单设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=require_setting&type=material_value_split_rule_setting,audit_level_split_rule_setting,warehouse_split_rule_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '根据医院实际运营管理需求，设置需求计划的拆单规则',
      },
      {
        id: '1605c473d0001f0',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-01-09 13:30:56',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '科室结账',
        configType: '自动结账',
        configName: '科室是否自动结账设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=department_setting&type=auto_settle_account_setting,auto_audit_settle_account_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际运营管理需求，设置科室是否自动结账',
      },
      {
        id: '1605c473d0001e6',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2023-12-22 09:59:14',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '欠货',
        configType: '供应商欠货',
        configName: '供应商欠货设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/SupplierOwinggoodsSet?categoryCode=organization_setting&type=own_setting,reminder_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '根据医院实际运营管理需求，设置供应商欠货耗材达到一定时间是否自动关闭',
      },
      {
        id: '1605c473d132221',
        createBy: '1',
        createTime: '2022-06-07 18:17:43',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-03-13 11:31:26',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '规格耗材',
        configType: '其他',
        configName: '不同物资类型的耗材在新建、修改时，要求设置',
        pageAddress:
          '{"type":"page","path":"/basic/materialInsertUpdateSetting/detail.ac?categoryCode=material_setting&type=material_insert_update_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '备注：根据医院运营的管理，设置不同的物资类型的耗材，创建要求',
      },
      {
        id: '1605c473d0001f7',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-01-29 11:22:14',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '配送出库',
        configType: '配送出库占用耗材设置',
        configName: '配送出库占用耗材设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=material_occupy_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark:
          '根据医院的实际运营管理，设置非散货耗材在新建出库单的时候，占用耗材的维度，是占用到批次库存，还是只占用到数量',
      },
      {
        id: '1605c473d0001e5',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-01-29 13:14:51',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '打印',
        configType: '打印设置',
        configName: '单据打印设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=print_setting&type=bill_print_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '根据医院实际运营管理需求，设置待审核状态的单据是否可以打印',
      },
      {
        id: '2022011700001',
        createBy: '0',
        createTime: '2022-03-05 17:39:30',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-02-05 15:35:53',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'HIS计费',
        configType: 'HIS计费设置',
        configName: 'spd消耗计费，耗材单价跟his收费项目不一致是否提醒计费护士',
        pageAddress:
          '{"type":"page","path":"/systemSetting/hisInterfaceSetting?categoryCode=his_interface_setting&type=price_reminder_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark:
          '备注：根据医院实际运营管理需求，设置spd计费时，耗材单价为0或者耗材单价（寄售耗材最新供货清单）跟his收费项目不一致时，是否提醒计费护士；',
      },
      {
        id: '202211240001',
        createBy: '1',
        createTime: '2022-12-13 12:23:41',
        updateBy: '20210928155804dfm8cu9y5',
        updateTime: '2024-03-29 15:11:11',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '配送出库',
        configType: '其它',
        configName: '出库单跨月提交设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/AcrossMonthSubmitSetting?categoryCode=center_warehouse_setting&type=across_month_submit_generate_new_order"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王金磊',
        remark: '根据医院实际运营管理，设置出库单跨月提交时，是否重新生成出库单',
      },
      {
        id: '1605c473d0001f1',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230227161240ze9whs9r0',
        updateTime: '2024-04-10 16:02:05',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '医院运营',
        configType: '人员设置',
        configName: '运营人员账号设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/OperatePersonNumberSet?categoryCode=person_setting&type=manage_person_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '张大千',
        remark: '根据每一个项目的实际需要，设置接收短信通知的运营人员的手机号',
      },
      {
        id: '2021111700001',
        createBy: '1',
        createTime: '2021-11-19 12:13:10',
        updateBy: '20210714094751yysmfrwqv',
        updateTime: '2024-03-07 14:28:25',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '打印',
        configType: '打印设置',
        configName: 'RFID打印服务设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/RfidPrintService?categoryCode=print_setting&type=rfid_print_service_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '佘玉诚',
        remark: '根据医院实际运营管理需求，设置RFID打印机服务地址及打印按钮名称;',
      },
      {
        id: '2021082400001',
        createBy: '1',
        createTime: '2021-09-06 09:24:07',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-03-12 15:47:03',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '入库验收',
        configType: '入库设置',
        configName: '入库UDI码校验设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=udi_check_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '测试人员',
        remark: '备注：根据医院的实际运营需求，设置厂商码管理的耗材入库的时候，udi码是否必须填写',
      },
      {
        id: '1605c473d000200',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-04-10 19:21:09',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '耗材设置',
        configType: '耗材单价一致性设置',
        configName: '同一耗材的不同供货清单单价是否是必须一致',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=material_setting&type=price_uniform_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '同一耗材不同供货清单的单价是否必须一致',
      },
      {
        id: '202104280000001',
        createBy: '1',
        createTime: '2021-04-28 14:49:02',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-04-02 17:17:10',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '耗材设置',
        configType: '可放回、可退货时间范围设置',
        configName: '可放回、可退货时间范围设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/PutbackGoodsSet?categoryCode=material_setting&type=pu_back_time_scope_setting,return_time_scope_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark:
          '备注：可放回、可退货的时间范围设置，用户可以设定退多久之前取用的耗材。 “可放回时间范围”可输入范围为大于0的正整数；  “可退货时间范围”可输入范围为大于0的正整数',
      },
      {
        id: '1605c473d0001fd',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '系统设置',
        configType: '系统设置',
        configName: '中山合同管理系统配置',
        pageAddress:
          '{"type":"input","path":"/basic/systemsetting/detail.ac?categoryCode=system_setting&type=contract_manage_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '中山合同管理系统配置',
      },
      {
        id: '1605c473d0001e2',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230221190256texemg0a6',
        updateTime: '2023-12-08 17:35:47',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '入库验收',
        configType: '其它',
        configName: '耗材验收时效性设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/MaterialAcceptTimeSet?categoryCode=center_warehouse_setting&type=material_effect_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: 'wjl',
        remark: '根据医院实际运营管理需求，设置每一种耗材的可验收最低效期',
      },
      {
        id: '202104280000002',
        createBy: '1',
        createTime: '2021-04-28 17:32:45',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-04-03 14:05:33',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'HIS计费',
        configType: 'HIS计费设置',
        configName: 'HIS成本科室取值',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=cost_department_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark:
          '选择“执行科室”时，his传过来的执行科室作为成本取值设置。选择“开单科室”时，his传过来的开单科室作为成本取值设置；选择“计费科室”时，his传过来的计费科室作为成本取值设置；默认值是执行科室。',
      },
      {
        id: '1605c473d0001f8',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230517165931j7bsbdr37',
        updateTime: '2024-04-03 14:49:00',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'HIS-ETL设置',
        configType: '其它',
        configName: 'HIS-ETL配置',
        pageAddress:
          '{"type":"input","path":"/basic/systemsetting/detail.ac?categoryCode=system_setting&type=etl_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '白惠文',
        remark: '根据医院的实际运营要求，设置HIS-ETL的接口地址',
      },
      {
        id: '2022011800001',
        createBy: '1',
        createTime: '2022-02-08 11:41:51',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-04-08 13:16:32',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'HIS计费',
        configType: 'HIS计费设置',
        configName: 'HIS出库科室取值',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=his_interface_setting&type=warehouse_out_department_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员1',
        remark:
          '选择“执行科室”时，his传过来的执行科室作为出库科室。选择“开单科室”时，his传过来的开单科室作为出库科室；选择“计费科室”时，his传过来的计费科室作为出库科室；默认值是执行科室。',
      },
      {
        id: '2021101400001',
        createBy: '1',
        createTime: '2021-10-26 12:30:01',
        updateBy: '20211028150439zqflkcvbk',
        updateTime: '2024-03-28 18:32:49',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '需求计划',
        configType: '其他',
        configName: '需求计划配送设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=require_setting&type=deliver_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '接口测试专用护士',
        remark:
          '备注：根据医院实际运营管理需求，设置需求计划是否支持多次配送；当设置为“是”的时候，代表需求计划申请的一种耗材可以支持多次配送；当设置为“否”的时候，代表需求计划申请的一种耗材只要配送一次，剩下的未配送的耗材就把未配送的量自动关闭。',
      },
      {
        id: '1605c473d0001ea',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-01-29 13:16:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '中心仓出库',
        configType: '打包设置',
        configName: '中心仓出库定数包是否自动打包',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=auto_package_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '根据医院实际运营管理需求，设置中心仓出库定数包是否是自动打包',
      },
      {
        id: '1605c473d0001fa',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20231011090805of0sm5y04',
        updateTime: '2024-03-25 15:57:42',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '打印',
        configType: '打印设置',
        configName: '第三方打印设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/ThirdPrintingSet?categoryCode=print_setting&type=print_template_address_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '任良硕',
        remark: '润乾服务器打印条码模板配置',
      },
      {
        id: '1605c473d123768',
        createBy: '1',
        createTime: '2022-03-29 12:07:05',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '供应商结账',
        configType: '供应商结账设置',
        configName: '供应商结账单中的会计期间取值设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=organization_setting&type=account_period_value_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际运营管理需求，设置在供应商结账的时候,供应商结账单里面的会计期间取值',
      },
      {
        id: '1605c473d000201',
        createBy: '1',
        createTime: '2021-04-06 16:36:35',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '结算管理',
        configType: '结转设置',
        configName: '结转设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=organization_setting&type=carry_over_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '会计期间结账时，判断是否有未审核的供应商结账单',
      },
      {
        id: '1605c473d0001fe',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '打印',
        configType: '打印设置',
        configName: 'RFID打印条码范围设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=print_setting&type=rfid_print_scope_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院的实际运营要求，设置哪些条码可以被打印为RFID条码',
      },
      {
        id: '1605c473d0001fc',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-04-10 13:33:26',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '科室收货',
        configType: '科室收货设置',
        configName: '科室自动收货设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/DepartmentReceivingSet?categoryCode=department_setting&type=auto_receive_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院的实际运营要求，设置哪类科室自动收货',
      },
      {
        id: '202209021641',
        createBy: '1',
        createTime: '2022-11-08 12:54:14',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-04-10 17:02:21',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '规格耗材字典',
        configType: '其它',
        configName: '规格耗材字典设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/MaterialDictionaryAddSetting?categoryCode=material_setting&type=fields_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark:
          '根据医院实际运营管理需求，设置新建规格耗材字典的要求；可以设置哪些字段显示不显示，设置哪些字段是否必填，设置字段的默认值等',
      },
      {
        id: '1605c473d000798',
        createBy: '1',
        createTime: '2022-03-14 16:20:49',
        updateBy: '1',
        updateTime: '2024-02-05 17:31:30',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '基础数据',
        configType: '临采耗材是否自动停用',
        configName: '临采耗材是否自动停用',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=material_setting&type=auto_stop_material_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '超级管理员',
        remark:
          '根据医院实际运营管理需求，设置临采耗材入库之后，中心仓入库单审核通过之后，是否可以自动停用供货清单',
      },
      {
        id: '202301050919',
        createBy: '1',
        createTime: '2023-02-08 13:25:59',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-03-13 17:31:48',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '采购计划',
        configType: '其他',
        configName: '库存补货中现有库存如何取值',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=inventory_replenishment_stock_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '根据医院实际运营管理需求，设置库存补货计算公式中现有库存如何取值',
      },
      {
        id: '202301281010',
        createBy: '1',
        createTime: '2023-02-22 11:09:14',
        updateBy: '20210928155804dfm8cu9y5',
        updateTime: '2024-03-29 15:06:39',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '消耗监管',
        configType: '其他',
        configName: '消耗限额中合计出库金额如何取值',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=limit_setting&type=department_limit_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王金磊',
        remark: '根据医院实际运营管理需求，设置消耗限额中的合计出库金额如何计算',
      },
      {
        id: '20220524102308bbf2b40045',
        createBy: '1',
        createTime: '2022-05-24 09:20:49',
        updateBy: '20210928155804dfm8cu9y5',
        updateTime: '2024-03-29 15:21:41',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '耗材设置',
        configType: '耗材调拨设置',
        configName: '已经登记发票的耗材是否可以调拨',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=material_setting&type=had_invoice_can_allot_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王金磊',
        remark: '已经登记发票的耗材是否可以调拨',
      },
      {
        id: '2022090100001',
        createBy: '1',
        createTime: '2022-09-22 11:36:01',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-03-29 17:35:01',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '需求计划',
        configType: '其它',
        configName: '需求计划跟配送出库关系设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/RequirePlanAndDeliverRelation?categoryCode=require_setting&type=require_plan_and_deliver_relation_setting,require_plan_and_deliver_relation_setting_2"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院实际运营管理需求，设置需求计划跟配送出库之间的关系',
      },
      {
        id: '160c84ac2000017',
        createBy: '1',
        createTime: '2022-01-04 11:47:41',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-04-11 10:39:10',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '发票登记',
        configType: '发票登记设置',
        configName: '发票登记设置',
        pageAddress:
          '{"type": "page","path": "/systemSetting/invoiceRegisterSet?categoryCode=invoice_register_setting&type=invoice_register_allow_center_warehouse_setting,invoice_register_allow_account_period_setting,invoice_register_invoice_no_limit_setting,invoice_register_allow_withdraw,invoice_register_split_account,invoice_add_time_setting,invoice_no_unique_setting,invoice_picture_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '根据医院的实际运营管理需求，设置发票登记的规范',
      },
      {
        id: '202211210001',
        createBy: '1',
        createTime: '2022-12-13 12:23:07',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-05-12 16:08:24',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '定数包',
        configType: '其它',
        configName: '定数包厂商码生成规则',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=fix_package_setting&type=manufacture_code_generate_strategy"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际运营管理，设置定数包厂商码的生成规则',
      },
      {
        id: '202209071112',
        createBy: '1',
        createTime: '2022-09-29 22:03:10',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2023-07-25 17:32:13',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '系统设置',
        configType: '报表服务设置',
        configName: '是否使用帆软报表设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=system_setting&type=report_forms_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员',
        remark: '根据医院实际运营管理需求，设置是否使用帆软报表',
      },
      {
        id: '202211161010',
        createBy: '1',
        createTime: '2022-12-13 12:23:41',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-04-09 10:19:53',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '采购计划',
        configType: '其他',
        configName: '采购计划是否补需求计划',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=auto_require_plan_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '根据医院实际运营管理，设置采购计划提交时，是否反向补需求计划',
      },
      {
        id: '2023042301430',
        createBy: '1',
        createTime: '2023-04-23 14:54:08',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-04-02 09:36:47',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '规格耗材字典',
        configType: '其它',
        configName: '规格耗材字典创建成功是否同时自动生成his收费项目编码',
        pageAddress:
          '{"type":"page","path":"/systemSetting/MaterialCreateSuccess2AutoCreateHISChargeItem?categoryCode=material_setting&type=his_code_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院运营管理需求设置规格字典创建成功时，是否自动生成his收费项目编码',
      },
      {
        id: '20230221174200002',
        createBy: '1',
        createTime: '2023-02-21 00:00:00',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-02-04 16:14:53',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '系统设置',
        configType: '系统设置',
        configName: '同步盘锦集成平台设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=system_setting&type=sync_pj_third_platform_yn"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark:
          '备注：根据医院实际运营管理需求，设置是否开启同步盘锦集成平台；如果设置为是，规格耗材、供货清单的一些节点操作时，会写入中间表数据，供ETL调用同步给盘锦集成平台；',
      },
      {
        id: '1605c473d0001d2',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230227210053svo8hulb2',
        updateTime: '2024-04-10 21:49:55',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '采购计划',
        configType: '拆单',
        configName: '采购计划拆单设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=organization_split_rule_setting,material_value_split_rule_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '丁冬医院超级管理员',
        remark: '根据医院实际运营管理需求，设置采购计划的拆单规则',
      },
      {
        id: '2021091700001',
        createBy: '1',
        createTime: '2021-10-26 12:27:27',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-03-29 13:55:11',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '配送出库',
        configType: '超量配送',
        configName: '是否可以超需求计划量配送',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=exceed_deliver_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '洪燕',
        remark:
          '备注：根据医院的实际运营需求，设置调用需求计划配送时，是否可以超过需求计划的量给科室配送；若设置为“否”则代表不可以超过科室需求量配送；若设置为“是”则代表可以超过科室需求量配送。',
      },
      {
        id: '1605c473dd32223',
        createBy: '1',
        createTime: '2022-07-04 14:01:10',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2024-04-11 09:14:57',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '入库验收',
        configType: '其他',
        configName: '不同物资类型耗材入库时，是否必须有供货清单',
        pageAddress:
          '{"type":"page","path":"/systemsetting/MustExistSuppliesContractSetting?categoryCode=center_warehouse_setting&type=must_exist_supplies_contract_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark: '不同物资类型耗材入库时，是否必须有供货清单',
      },
      {
        id: '2021090100001',
        createBy: '1',
        createTime: '2021-09-07 18:17:19',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-04-10 13:34:16',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: 'HIS计费',
        configType: 'HIS计费设置',
        configName: '计费扫码设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/HisChargeContrastUDIOrCode?categoryCode=his_interface_setting&type=scan_barcode_setting"}',
        sort: null,
        createUserName: '超级管理员',
        updateUserName: '洪燕',
        remark: '计费时使用UDI条码还是使用院内码进行扫码计费',
      },
      {
        id: '1605c473d0001d4',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210928155804dfm8cu9y5',
        updateTime: '2024-03-29 15:27:18',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '采购订单',
        configType: '拆单',
        configName: '采购订单拆单设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=purchase_setting&type=split_rule_setting,material_type_split_rule_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王金磊',
        remark: '根据医院实际运营管理需求，设置采购订单的拆单规则',
      },
      {
        id: '1605c473d0001e7',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20230222151522oe4x9bwy6',
        updateTime: '2024-04-10 14:43:02',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '供应商结账',
        configType: '供应商结账',
        configName: '供应商结账设置',
        pageAddress:
          '{"type":"page","path":"/systemsetting/OrganizationSettleAccountRules?categoryCode=organization_setting&type=settle_account_rule_setting,settle_account_method_setting,settle_account_material_kind_setting,settle_account_unit_setting,settle_account_batch_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '测试人员1',
        remark: '根据医院实际运营管理需求，设置供应商结账的流程',
      },
      {
        id: '1605c473d0001d7',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20211028150439zqflkcvbk',
        updateTime: '2024-03-29 13:44:59',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '需求计划',
        configType: '单据审核设置',
        configName: '需求计划审核设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/RequirePlanExamineSet?categoryCode=require_setting&type=purchase_audit_setting,stock_audit_setting,replenish_audit_setting,month_plan_audit_setting,quarter_plan_audit_setting,year_plan_audit_setting,urgent_plan_audit_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '接口测试专用护士',
        remark: '根据医院实际运营管理需要，设置需求计划的审核设置',
      },
      {
        id: '1605c473d0001d5',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-04-10 13:33:26',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '配送出库单',
        configType: '拆单',
        configName: '配送出库单拆单设置',
        pageAddress:
          '{"type":"page","path":"/systemSetting/DistributionSplitBill?categoryCode=center_warehouse_setting&type=record_split_rule_setting,material_kind_split_rule_setting,material_manage_split_rule_setting,purchase_order_split_rule_setting,purchase_style_split_rule_setting,sale_yn_split_rule_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院实际运营管理需求，设置配送出库单的拆单规则',
      },
      {
        id: '1605c473d0001e8',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210928155804dfm8cu9y5',
        updateTime: '2024-03-29 15:28:54',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '需求计划',
        configType: '其它',
        configName: '可拣货出库、采购的需求计划类型设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=require_setting&type=pick_plan_type_setting,purchase_plan_type_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王金磊',
        remark: '根据医院的实际原因管理需求，设置可拣货出库、采购的需求计划的类型',
      },
      {
        id: '1605c473d0001db',
        createBy: '1',
        createTime: '2021-03-31 18:33:28',
        updateBy: '20210726105607y7mlur6id',
        updateTime: '2024-04-01 10:12:19',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '退库单',
        configType: '单据审核设置',
        configName: '退库单审核设置',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=department_setting&type=audit_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '洪燕',
        remark: '根据医院实际运营管理需求，设置退库库单审核设置',
      },
      {
        id: '1605c473d111768',
        createBy: '1',
        createTime: '2022-06-13 17:28:21',
        updateBy: '20211028150439zqflkcvbk',
        updateTime: '2024-03-28 18:22:44',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '配送出库',
        configType: '其他',
        configName: '配送出库时，定数包管理耗材是否显示一物一码',
        pageAddress:
          '{"type":"select","path":"/basic/systemsetting/detail.ac?categoryCode=center_warehouse_setting&type=fix_package_show_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '接口测试专用护士',
        remark:
          '备注：根据医院实际运营管理需求，设置新建配送出库时，定数包耗材是否显示院内码；如果设置为是，则新建配送出库时，定数包的厂商码、院内码都显示；如果设置为否，则新建配送出库时，定数包只显示厂商码；',
      },
      {
        id: '2021061100001',
        createBy: '1',
        createTime: '2021-06-11 16:24:23',
        updateBy: '20230523165821g0c67oqb0',
        updateTime: '2023-12-05 14:58:39',
        searchValue: null,
        orderKey: null,
        orderValue: null,
        params: {},
        hospitalId: 'ec6d221af73d0206dfafaddaa2887c69',
        hospitalAreaId: null,
        functionModule: '耗材设置',
        configType: '耗材超时提醒设置',
        configName: '设定超时提醒时间',
        pageAddress:
          '{"type":"page","path":"/systemSetting/MaterialOvertimeSet?categoryCode=material_setting&type=timing_setting,slow_moving_warning_setting,expire_warning_setting,stop_warning_setting"}',
        sort: null,
        createUserName: 'admin',
        updateUserName: '王喵喵1',
        remark:
          '根据医院实际运营管理需求，近效期耗材提醒；呆滞品提醒，耗材取用超时未计费提醒；规格耗材字典停用预警提醒',
      },
    ],
  },
};
